name: ibook
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #BASE
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  intl: ^0.17.0

  #UI
  cached_network_image: ^3.2.0
  flutter_staggered_animations: 1.0.0
  flutter_vector_icons: ^1.0.0

  #STATE MANAGEMENT
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

  #CONNECTIVITY
  http: ^0.13.4
  connectivity_plus: ^2.2.1
  package_info_plus: ^1.4.0
  share_plus: ^4.0.3
  store_redirect: ^2.0.1

  # WEB TOOLS
  flutter_inappwebview: ^5.3.2

  # ADS
  google_mobile_ads: ^1.1.0
  facebook_audience_network: ^1.0.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.3.0

  # LAUNCH URL
  url_launcher: ^6.0.20

  #Database
  shared_preferences: ^2.0.13

  fluttertoast: ^8.0.9
  html: ^0.15.0
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: ^0.6.1

  #PDF
  syncfusion_flutter_pdfviewer: ^19.4.56-beta

  #Localization
  flutter_localizations:
    sdk: flutter
  flutter_flushbar: ^0.0.2
  provider: ^6.0.0
  confirm_dialog: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  #flutter packages pub run build_runner build --delete-conflicting-outputs

  flutter_lints: ^1.0.4
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/flag/
